refactor: 월간 캘린더 UI 수정
payhereinc/react-native-big-calendar pull request #1
Opened 2021-11-24 08:01 UTC by mandarinduk

### Summary

- 월간 캘린더 UI 수정

### Story

- 월간 캘린더 UI 수정

### Changes

- 월간 캘린더 UI 수정

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionally)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test
- [ ] Documentation
- [X] Refactoring

### Screenshots or Videos

### How to test (Optional)
*How to test this PR*

2021-11-24 08:22 UTC, minsun2 approved these changes

2021-11-24 08:23 UTC, Price3258 requested changes

2021-11-24 08:23 UTC, Price3258 commented on src/components/CalendarContainer.tsx
> +          onResponderTerminationRequest={() => false}
ask : 이건 false를 보내야하는건가요??

2021-11-24 08:27 UTC, mandarinduk commented on src/components/CalendarContainer.tsx
> +          onResponderTerminationRequest={() => false}
50895ef
스크롤 이벤트가 잘 안돼서 해결하고자 넣었던 부분인데
해결되지 않아 삭제했습니다!

2021-11-24 09:43 UTC, wontaezia approved these changes

2021-11-24 11:34 UTC, hongsa requested changes

2021-11-24 11:34 UTC, hongsa commented on src/components/CalendarHeaderForMonthView.tsx
> +            )}
P2
인라인으로 된 style이나 render되는 부분도 함수로 빼면 더 좋을 것 같습니다~

2021-11-25 01:45 UTC, minozzang508 requested changes

2021-11-25 01:45 UTC, minozzang508 commented on src/components/CalendarBodyForMonthView.tsx
> +                            : '#333333',
p2; 
3항연산자가 너무 많은데 `()`를 통해서 연산 순위를 명확히 보여주거나 분리하는게 어떨까요?
추후 다른 사람이 수정할때 어려울것같습니다.

2021-11-25 06:58 UTC, mandarinduk commented on src/components/CalendarHeaderForMonthView.tsx
> +            )}
acaba45
수정 했습니다!

2021-11-25 06:58 UTC, mandarinduk commented on src/components/CalendarBodyForMonthView.tsx
> +                            : '#333333',
acaba45
수정 했습니다!

2021-11-25 07:16 UTC, minozzang508 approved these changes

2021-11-25 08:00 UTC, hongsa approved these changes

2021-11-25 08:13 UTC, Price3258 approved these changes

2021-11-25 08:13 UTC, merged